NEWHOPE_N = 1024

NEWHOPE_Q = 12289
NEWHOPE_K = 8

NEWHOPE_SYMBYTES = 32

NEWHOPE_POLYBYTES = (14 * NEWHOPE_N) // 8
NEWHOPE_POLYCOMPRESSEDBYTES = (3 * NEWHOPE_N) // 8

NEWHOPE_CPAPKE_PUBLICKEYBYTES = NEWHOPE_POLYBYTES + NEWHOPE_SYMBYTES
NEWHOPE_CPAPKE_SECRETKEYBYTES = NEWHOPE_POLYBYTES
NEWHOPE_CPAPKE_CIPHERTEXTBYTES = NEWHOPE_POLYBYTES + NEWHOPE_POLYCOMPRESSEDBYTES
NEWHOPE_CPAPKE_PLAINTEXTBYTES = NEWHOPE_SYMBYTES

NEWHOPE_CPAKEM_PUBLICKEYBYTES = NEWHOPE_CPAPKE_PUBLICKEYBYTES
NEWHOPE_CPAKEM_SECRETKEYBYTES = NEWHOPE_CPAPKE_SECRETKEYBYTES
NEWHOPE_CPAKEM_CIPHERTEXTBYTES = NEWHOPE_CPAPKE_CIPHERTEXTBYTES
NEWHOPE_CPAKEM_PLAINTEXTBYTES = NEWHOPE_CPAPKE_PLAINTEXTBYTES

NEWHOPE_CCAKEM_PUBLICKEYBYTES = NEWHOPE_CPAPKE_PUBLICKEYBYTES
NEWHOPE_CCAKEM_SECRETKEYBYTES = NEWHOPE_CPAPKE_SECRETKEYBYTES + NEWHOPE_CPAPKE_PUBLICKEYBYTES + 2 * NEWHOPE_SYMBYTES
NEWHOPE_CCAKEM_CIPHERTEXTBYTES = NEWHOPE_CPAPKE_CIPHERTEXTBYTES + NEWHOPE_SYMBYTES
NEWHOPE_CCAKEM_PLAINTEXTBYTES = NEWHOPE_CPAPKE_PLAINTEXTBYTES
